"""initial schema

Revision ID: 3cf7794531ac
Revises: 
Create Date: 2026-07-04 17:41:09.351649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf7794531ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('crop_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=64), nullable=False),
    sa.Column('ph_min', sa.Float(), nullable=False),
    sa.Column('ph_max', sa.Float(), nullable=False),
    sa.Column('ec_min', sa.Float(), nullable=False),
    sa.Column('ec_max', sa.Float(), nullable=False),
    sa.Column('water_temp_min', sa.Float(), nullable=False),
    sa.Column('water_temp_max', sa.Float(), nullable=False),
    sa.Column('air_temp_min', sa.Float(), nullable=False),
    sa.Column('air_temp_max', sa.Float(), nullable=False),
    sa.Column('humidity_min', sa.Float(), nullable=False),
    sa.Column('humidity_max', sa.Float(), nullable=False),
    sa.Column('water_level_min', sa.Float(), nullable=False),
    sa.Column('water_level_max', sa.Float(), nullable=False),
    sa.Column('light_min', sa.Float(), nullable=False),
    sa.Column('light_max', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_name')
    )
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('site_type', sa.Enum('school', 'community', name='sitetype'), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('crop_profile_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['crop_profile_id'], ['crop_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('connectivity', sa.String(length=16), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('school_operator', 'cb_operator', 'coordinator', 'agronomist', 'admin', name='role'), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('preferred_channel', sa.Enum('dashboard', 'email', 'sms', 'ussd', name='channel'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('parameter', sa.Enum('ph', 'ec', 'water_temp', 'air_temp', 'humidity', 'water_level', 'light', name='parameter'), nullable=False),
    sa.Column('state', sa.Enum('normal', 'watch', 'alert_raised', 'notification_sent', 'acknowledged', 'resolved', 'closed', name='alertstate'), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('trigger_value', sa.Float(), nullable=False),
    sa.Column('band_min', sa.Float(), nullable=False),
    sa.Column('band_max', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('parameter', sa.Enum('ph', 'ec', 'water_temp', 'air_temp', 'humidity', 'water_level', 'light', name='parameter'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['sensor_nodes.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_readings_site_param_ts', 'readings', ['site_id', 'parameter', 'ts'], unique=False)
    op.create_index(op.f('ix_readings_ts'), 'readings', ['ts'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('dashboard', 'email', 'sms', 'ussd', name='channel'), nullable=False),
    sa.Column('recipient', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_index(op.f('ix_readings_ts'), table_name='readings')
    op.drop_index('ix_readings_site_param_ts', table_name='readings')
    op.drop_table('readings')
    op.drop_table('auth_tokens')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('sensor_nodes')
    op.drop_table('sites')
    op.drop_table('crop_profiles')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
